[package]
name = "template-rust"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Longo"]
license = "GPL-3.0-or-later"
repository = "https://github.com/andreaslongo/template-rust"

[dependencies]
anstream = "0.6.4"
clap = { version = "4.4.6", features = ["derive"] }
owo-colors = "3.5.0"
