[project]
name = "template-rust"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[environments]
default = { solve-group = "default-group", features = ["dev"] }
prod = { solve-group = "default-group", features = ["prod"] }

[tasks]
dev = { depends-on = ["fmt", "git-hooks", "lint", "test"] }
start = "cargo run"
clean = "cargo clean"

[dependencies]
rust = ">=1.81.0,<2"
# openssl = ">=3.3.2,<4"
# compilers = ">=1.8.0,<2"  # for openssl
# pkg-config = ">=0.29.2,<0.30"  # for openssl

[feature.prod.tasks]
# TODO: Use cargo build --frozen or --locked.
build = "cargo build --release"

[feature.dev.tasks]
fmt = "cargo fmt"
lint = "cargo clippy --all-targets"
test = "cargo test"
git-hooks = "pre-commit run --all"
git-hooks-update = "pre-commit autoupdate --freeze"

[feature.dev.dependencies]
git = "*"  # required for running git hooks via pre-commit
pre-commit = "*"
